name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    uses: "./.github/workflows/forge-build.yml"

  test:
    needs: ["build"]
    uses: "./.github/workflows/forge-test.yml"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
