name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-build.yaml@e78620dc"

  test:
    needs: ["build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@e78620dc"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
