name: test

on:
  push:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    # uses: "./.github/workflows/forge-build.yaml"
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-build.yaml@062d94808c675ec5da653707170f922cbce5c90f"

  test-multi-account:
    needs: ["build"]
    # uses: "./.github/workflows/forge-test-multi-account.yaml"
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-multi-account.yaml@062d94808c675ec5da653707170f922cbce5c90f"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"

  test-simulate:
    needs: ["build"]
    uses: "./.github/workflows/forge-test-simulate.yaml"
    # uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-simulate.yaml@062d94808c675ec5da653707170f922cbce5c90f"

    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
